services:
  tailscale-tsidp:
    container_name: tailscale-tsidp
    image: ghcr.io/prymalinstynct/tsidp:v1.78.1
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - TS_AUTHKEY=
    volumes:
      - ./config:/config/tsidp
